name: Check SPARQL queries
on: [pull_request, workflow_call, workflow_dispatch]

permissions:
  contents: read

jobs:

  check:
    name: Run SPARQL checks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install tester
      run: wget "https://github.com/sib-swiss/sparql-examples-utils/releases/download/v2.0.19/sparql-examples-utils-2.0.19-uber.jar" -O sparql-examples-utils.jar

    - name: Run tests
      run: java -jar sparql-examples-utils.jar test --input-directory=examples/
